In [159]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [160]:
dataset = pd.read_csv('datasetPreprocessing.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [161]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Indonesia' 20.0 50000.0]
 ['France' 22.0 45000.0]
 ['Indonesia' 45.0 21400.0]
 ['Indonesia' 29.0 40000.0]]


In [162]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'No']


In [163]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [164]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 56184.61538461538]
 ['France' 35.0 58000.0]
 ['Spain' 35.76923076923077 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Indonesia' 20.0 50000.0]
 ['France' 22.0 45000.0]
 ['Indonesia' 45.0 21400.0]
 ['Indonesia' 29.0 40000.0]]


In [165]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))


In [166]:
print(x)

[[1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 56184.61538461538]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 35.76923076923077 52000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 20.0 50000.0]
 [1.0 0.0 0.0 0.0 22.0 45000.0]
 [0.0 0.0 1.0 0.0 45.0 21400.0]
 [0.0 0.0 1.0 0.0 29.0 40000.0]]


In [167]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [168]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 1 0 0]


In [169]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [170]:
print(x_train)

[[0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 20.0 50000.0]
 [0.0 1.0 0.0 0.0 40.0 56184.61538461538]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 45.0 21400.0]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 29.0 40000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 22.0 45000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]]


In [171]:
print(x_test)

[[0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 35.76923076923077 52000.0]]


In [172]:
print(y_train)

[0 0 1 1 0 0 0 1 0 1 1]


In [173]:
print(y_test)

[0 1 0]


In [174]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [175]:
print(x_train)

[[0.0 1.0 0.0 -0.316227766016838 -0.4791502965599001
  -0.003363442280190084]
 [0.0 0.0 1.0 -0.316227766016838 -1.5547938194494721 -0.25650672968398974]
 [0.0 1.0 0.0 -0.316227766016838 0.5964932263296719 0.13489173776342347]
 [0.0 0.0 0.0 3.16227766016838 -0.8018433534267717 -0.38307837338588957]
 [0.0 0.0 1.0 -0.316227766016838 1.1343149877744578 -2.066481234621157]
 [1.0 0.0 0.0 -0.316227766016838 1.0267506354855007 1.1357813510369084]
 [0.0 0.0 1.0 -0.316227766016838 -0.5867146488488574 -0.8893649481934889]
 [1.0 0.0 0.0 -0.316227766016838 0.2738001694628003 0.8193522417821588]
 [0.0 1.0 0.0 -0.316227766016838 1.6721367492192438 1.8319253913973574]
 [1.0 0.0 0.0 -0.316227766016838 -1.3396651148715577 -0.5729358389387393]
 [1.0 0.0 0.0 -0.316227766016838 0.058671464884885886 0.24977984512360957]]


In [195]:
print(x_test)

[[0.0 0.0 0.0 0.7071067811865476 -0.4869407000953254 -0.2672612419124244]
 [1.0 0.0 0.0 -1.414213562373095 1.3933253695796926 1.3363062095621219]
 [0.0 0.0 0.0 0.7071067811865476 -0.9063846694843684 -1.0690449676496976]]
